// services.js
export const services = [
    'Regular House Cleaning',
    'Spring Cleaning',
    'Deep House Cleaning',
    'One Time Regular Cleaning',
    'Move In Cleaning',
    'Move Out Cleaning',
    'Condo - Apartment Cleaning',
    'Post Construction Cleaning',
    'Post Renovation Cleaning',
    'Office Cleaning',
    'Cleaning And Organization',
    'Short Term Rental & Airbnb',
    'Declutter',
    'Preparation For Sale',
    'Staging Basic',
    'Add On & Special Requests',
    'Sanitize Service',
  ];
  
  export const extraServices = [
    { label: 'Room', value: 'Room', price: 25 },
    { label: 'Bathroom', value: 'Bathroom', price: 24 },
    { label: '1/2 Bathroom', value: '1/2 Bathroom', price: 12 },
    { label: 'Window and tracks', value: 'Window and tracks', price: 8 },
    { label: 'Window and screen', value: 'Window and screen', price: 12 },
    { label: 'Fridge', value: 'Fridge', price: 50 },
    { label: 'Stove', value: 'Stove', price: 60 },
    { label: 'Heavy duty', value: 'Heavy duty', price: 100 },
    { label: 'Air Vents', value: 'Air Vents', price: 20 },
    { label: 'Nick Nacks', value: 'Nick Nacks', price: 30 },
    { label: 'Balconies Swept', value: 'Balconies Swept', price: 12 },
    { label: 'Blinds Wiped B', value: 'Blinds Wiped B', price: 30 },
    { label: 'Baseboards', value: 'Baseboards', price: 50 },
    { label: 'Wall Washing', value: 'Wall Washing', price: 55 },
    { label: 'Basement', value: 'Basement', price: 60 },
    { label: 'Linen Changing', value: 'Linen Changing', price: 7 },
  ];